### ISSUE TITLE
E121: Undefined variable: :AutoHlsearch

### ISSUE THREAD

**Issue by Fildo7525** [asiryk/auto-hlsearch.nvim#4]
every time I try hitting n or N this issue pops up. I tried fix it however I am no so good in neovim API and lua. But the issue is in the mapping of the keys. keymap.rhs is nill. Not sure if this should be like that or not.

**Comment by asiryk** [comment]
Hi @Fildo7525! Thanks for using the plugin! Please, give me a little bit more information on how to reproduce this. Do you use the default settings? Did you call the setup() function?

**Comment by Fildo7525** [comment]
I just pu it in the packer and called setup with no arguments that is all

**Comment by asiryk** [comment]
@Fildo7525 that is weird...
can you please try changing [line 10](https://github.com/asiryk/auto-hlsearch.nvim/blob/main/lua/auto-hlsearch.lua#L10) in your locally downloaded auto-hlsearch.nvim

from 
```lua
if keymap then
```

to
```lua
if keymap and keymap.rhs then
```

and tell me if the issue is still around

the default path where packer is installing the plugin is `~/.local/share/nvim/site/pack/packer/start/auto-hlsearch.nvim`

**Comment by Fildo7525** [comment]
You works like a charm now thanks

**Comment by asiryk** [comment]
@Fildo7525 Nice! I fixed it in the plugin, you can `:PackerSync` to update it. And thanks for using the plugin <3
